[package]
name = "redis-clone"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
bytes = "1.9.0"
env_logger = "0.11.6"
log = "0.4.25"
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "net", "io-util", "sync"] }
